INSERT INTO MOVIES (NAME, SYNOPSIS, PHOTO, CATEGORY)
VALUES 
('Vingadores Ultimato', 'Ap\u00f3s Thanos eliminar metade das criaturas vivas, os Vingadores precisam lidar com a dor da perda de amigos e seus entes queridos. Com Tony Stark (Robert Downey Jr.) vagando perdido no espa\u00e7o sem \u00e1gua nem comida, Steve Rogers (Chris Evans) e Natasha Romanov (Scarlett Johansson) precisam liderar a resist\u00eancia contra o tit\u00e3 louco.', 'https:\/\/sujeitoprogramador.com\/r-api\/img\/filme0.png', 'Science_Fiction'),
('Shazam!', 'Billy Batson (Asher Angel) tem apenas 14 anos de idade, mas recebeu de um antigo mago o dom de se transformar num super-her\u00f3i adulto chamado Shazam (Zachary Levi). Ao gritar a palavra SHAZAM!, o adolescente se transforma nessa sua poderosa vers\u00e3o adulta para se divertir e testar suas habilidades. Contudo, ele precisa aprender a controlar seus poderes para enfrentar o malvado Dr. Thaddeus Sivana (Mark Strong).', 'https:\/\/sujeitoprogramador.com\/r-api\/img\/filme1.png', 'Science_Fiction'),
('O Primeiro Homem', 'A vida do astronauta norte-americano Neil Armstrong (Ryan Gosling) e sua jornada para se tornar o primeiro homem a andar na Lua. Os sacrif\u00edcios e custos de Neil e toda uma na\u00e7\u00e3o durante uma das mais perigosas miss\u00f5es na hist\u00f3ria das viagens espaciais.', 'https:\/\/sujeitoprogramador.com\/r-api\/img\/filme3.png', 'War'),
('Mission: Impossible \u2013 Fallout', 'Obrigado a unir for\u00e7as com o agente especial da CIA August Walker (Henry Cavill) para mais uma miss\u00e3o imposs\u00edvel, Ethan Hunt (Tom Cruise) se v\u00ea novamente cara a cara com Solomon Lane (Sean Harris) e preso numa teia que envolve velhos conhecidos movidos por interesses misteriosos e contatos de moral duvidosa.', 'https:\/\/sujeitoprogramador.com\/r-api\/img\/filme4.png', 'Science_Fiction'),
('The Meg', 'Na fossa mais profunda do Oceano Pac\u00edfico, a tripula\u00e7\u00e3o de um submarino fica presa dentro do local ap\u00f3s ser atacada por uma criatura pr\u00e9-hist\u00f3rica que se achava estar extinta, um tubar\u00e3o de mais de 20 metros de comprimento, o Megalodon. ', 'https:\/\/sujeitoprogramador.com\/r-api\/img\/filme5.png', 'Mystery'),
('Venom', 'San Francisco, Estados Unidos. Eddie Brock (Tom Hardy) \u00e9 um jornalista investigativo, que tem um quadro pr\u00f3prio em uma emissora local. Um dia, ele \u00e9 escalado para entrevistar Carlton Drake (Riz Ahmed), o criador da Funda\u00e7\u00e3o Vida, que tem investido bastante em miss\u00f5es espaciais de forma a encontrar poss\u00edveis usos medicinais para a humanidade. ', 'https:\/\/sujeitoprogramador.com\/r-api\/img\/filme6.png', 'Science_Fiction'),
('Pacific Rim: A Revolta', 'Filho de Stacker Pentecost (Idris Elba), respons\u00e1vel pelo comando do programa Jaeger, Jake (John Boyega) era um promissor talento do programa de defesa, mas abandonou o treinamento e entrou no mundo do crime ao vasculhar ferros-velhos em busca de pe\u00e7as de rob\u00f4s abandonados.', 'https:\/\/sujeitoprogramador.com\/r-api\/img\/filme7.png', 'Science_Fiction');
